apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: background-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: ghcr.io/kyverno/background-controller
    newTag: v1.10.0@sha256:603ea1d0636c96b2d4f95b2ecad75abe930ffe786f528008ea9bd6da15b195ff
