apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.10.0@sha256:59a01a747f3efd6d3356ab1fad19af2b71b604289adee6589bec600933d01a0e
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.10.0@sha256:81aa67584e1c71e83429f31fe1bc3c99550418639ba6e6735aea07bce9a4c7c8
