apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: kyverno
resources:
  - ./config
  - ./crds
  - ./rbac
  - ./admission-controller
  - ./background-controller
  - ./reports-controller
