apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: config
  app.kubernetes.io/part-of: kyverno
configMapGenerator:
  - name: kyverno
    options:
      disableNameSuffixHash: true
    literals:
      - excludeGroups=system:nodes
      - >-
        resourceFilters=
          [Event,*,*]
          [Node,*,*]
          [Node/*,*,*]
          [APIService,*,*]
          [APIService/*,*,*]
          [TokenReview,*,*]
          [SubjectAccessReview,*,*]
          [SelfSubjectAccessReview,*,*]
          [Binding,*,*]
          [Pod/binding,*,*]
          [ReplicaSet,*,*]
          [ReplicaSet/*,*,*]
          [AdmissionReport,*,*]
          [AdmissionReport/*,*,*]
          [ClusterAdmissionReport,*,*]
          [ClusterAdmissionReport/*,*,*]
          [BackgroundScanReport,*,*]
          [BackgroundScanReport/*,*,*]
          [ClusterBackgroundScanReport,*,*]
          [ClusterBackgroundScanReport/*,*,*]
  - name: kyverno-metrics
    options:
      disableNameSuffixHash: true
    literals:
      - namespaces={"exclude":[],"include":[]}
