apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: rbac
resources:
  - policies.yaml
  - policyreports.yaml
  - reports.yaml
  - updaterequests.yaml
